### ISSUE TITLE
Magic Missile alternate attack does not consume any Mana

### ISSUE THREAD

**Issue by Dudejo** [whirledtsar/Hexen-2---Shadows-of-Chaos-fork#45]
The red lightning attack does not consume any Mana. I'm not sure if this is intentional, considering the attack is strictly better than the starting Sickle weapon.

EDIT : Is the Mana drain tied to the Health absorption? The damage to target happens whether Health is absorbed or not.

**Comment by whirledtsar** [comment]
Yes, its intentional that it only takes mana if the attack drains health (which only happens if you have low health or a Tome activated). I can investigate further how balanced this is in practice.
