### ISSUE TITLE
My opinion about the lower limit of inventory items.

### ISSUE THREAD

**Issue by Dudejo** [whirledtsar/Hexen-2---Shadows-of-Chaos-fork#46]
I saw in the Readme how you justified the lowered capacities as an attempt to encourage using them instead of hoarding.

Personally, what limits me from using items is either because they're not particularly useful to me or because I think they're overkill. Otherwise, I'm not particularly shy about using them when I have large reserves.

If I only have a few at a time, I start thinking in a loop : "I can't use it now, I might not find another. What if I need it later against the boss or something?". Then I start trying to make do with low-cost tools and forget about my items entirely.

Because of that, I think that increasing the inventory capacity for items is what will encourage people to use them more.

**Comment by whirledtsar** [comment]
Hm, I understand your rationale but disagree. In the game you most certainly WILL find another artifact - they give you more than enough. The lowered carrying capacity is based on the same logic as Heretic. In that game, your inventory resets to 1 after each level. So if you have 2 of an item, you're motivated to use it soon so it doesn't go to waste. Here, the idea is to motivate the player to use them frequently so they don't pass by items without being able to pick them up.
