### ISSUE TITLE
Some enemies stop attacking

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [whirledtsar/Hexen-2---Shadows-of-Chaos-fork#98]
I noticed some enemies stay in loop and stop attacking the player. One of them is the WereJaguar (I'm not sure if this happens with other enemies with uHexen2. With HoT this happened with the Black WereJaguar and the Golems too).

Also I don't know why I can't upload the image, but he stays roaring indefinitely.

**Comment by whirledtsar** [comment]
Should be fixed now: https://github.com/whirledtsar/Hexen-2---Shadows-of-Chaos-fork/commit/ff10acb22d7e0e423001b8295471ace231aa3ae2
